<a href="https://colab.research.google.com/github/mysticizhere/ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]], dtype='int16')

In [5]:
print(b)

[[1 2 3]
 [4 5 6]]


In [6]:
# Get Dimensions 
a.ndim

1

In [7]:
b.ndim

2

In [8]:
# Get Shape
a.shape

(3,)

In [9]:
b.shape

(2, 3)

In [10]:
# Get Type
a.dtype

dtype('int64')

In [11]:
b.dtype

dtype('int16')

In [12]:
#Get Size
a.itemsize

8

In [13]:
b.itemsize

2

In [14]:
a.nbytes

24

In [15]:
b.size * b.itemsize

12

In [16]:
b.size
#No of elements

6

In [17]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
# Get a specific Element [r, c]
c[1,5]

13

In [19]:
# Get a specific Row [r, :]
c[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [20]:
# Get a specific Column [:, c]
c[:, 2]

array([ 3, 10])

In [21]:
# Getting Fancy [startIndex : endIndex : stepSize]
c[0,1:6:2]

array([2, 4, 6])

In [22]:
c[1,5] = 20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [23]:
c[:, 2] = 5
print(c)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [24]:
c[:, 2] = [7,6]
print(c)

[[ 1  2  7  4  5  6  7]
 [ 8  9  6 11 12 20 14]]


In [25]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
# 3D array d
# Get specific element ( work outside in ) [array , row, column]
d[0,1,1]

4

In [27]:
d[0, :, :]

array([[1, 2],
       [3, 4]])

In [28]:
d[1,:,: ]

array([[5, 6],
       [7, 8]])

In [29]:
d[0,:,1]

array([2, 4])

In [30]:
d[:,1,1]

array([4, 8])

In [31]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [34]:
# All 1s matrix
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [35]:
# Any other Number
np.full((2,2,2), 99)

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [37]:
# Any other Number (full_like i.e shape like another array)
np.full_like(c, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [38]:
# Random Decimal Numbers
np.random.rand(4,3)

array([[0.81275946, 0.27209288, 0.83104577],
       [0.94590793, 0.85138588, 0.24899835],
       [0.5223737 , 0.83548739, 0.48348395],
       [0.75412216, 0.03428716, 0.82908509]])

In [39]:
# Random Decimal Numbers shaped like
np.random.random_sample(c.shape)

array([[0.32887123, 0.78613021, 0.26621031, 0.15921454, 0.14071224,
        0.40478983, 0.13813766],
       [0.69151037, 0.82540533, 0.48965064, 0.63637741, 0.9815663 ,
        0.99969018, 0.72160432]])

In [40]:
# Random Integer Values
np.random.randint(2,85,size=(3,3))

array([[22, 41, 15],
       [ 4, 22, 35],
       [17, 76, 69]])

In [41]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
# Repeat entries in array in certain Way
#Axis = 0 ( Verticle )
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [44]:
#Axis = 1 ( Flat )
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [ ]:
# Making the following Array without Manual Typing
# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1 
# 1 0 0 0 1
# 1 1 1 1 1

In [45]:
# Solution

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
##### Be Careful when copying arrays !!

In [47]:
# Lets look at one example
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [48]:
# Lets make changes to b
b[0] = 100
b

array([100,   2,   3])

In [50]:
# Caution !!!! (a also got changed)
a

array([100,   2,   3])

In [51]:
# 'b' is basically pointing to 'a' instead of being another copy of 'a' with a different address 

In [53]:
# Fix 
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


In [54]:
# MATHS

In [55]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [56]:
a+2

array([3, 4, 5, 6])

In [57]:
a-2

array([-1,  0,  1,  2])

In [58]:
a*2

array([2, 4, 6, 8])

In [59]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [60]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [61]:
a **2

array([ 1,  4,  9, 16])

In [62]:
a **3

array([ 1,  8, 27, 64])

In [63]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [64]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [65]:
# Linear Algebra

In [66]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [68]:
# Matrix Multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [69]:
# Find Determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [70]:
d = np.matmul(a,b)
np.linalg.det(d)

0.0

In [71]:
# Min and Max
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.min(stats)

1

In [73]:
np.max(stats)

6

In [74]:
np.min(stats, axis = 1)

array([1, 4])

In [75]:
np.sum(stats)

21

In [79]:
# Along columns
np.sum(stats, axis = 0)


array([5, 7, 9])

In [78]:
# Along rows
np.sum(stats, axis = 1)

array([ 6, 15])

In [80]:
# Reorganizing Arrays

In [82]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [83]:
before.shape


(2, 4)

In [86]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [88]:
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [89]:
# Vertically Stacking Vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [90]:
v = np.vstack([v2,v2,v1])
print(v)

[[5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


In [91]:
# Horizontal Stacking Vectors
h = np.hstack([v2,v2,v1])
print(h)

[5 6 7 8 5 6 7 8 1 2 3 4]


In [ ]:
# Load Data From File

In [98]:
fileData = np.genfromtxt('dataTest.txt', delimiter=',')
fileData

array([[  1.,   2.,   3.,   4.,   6.,   7.,   4.,   3.,   5.,  79.,   3.,
          4.,   6.],
       [ 43.,   4.,   6.,  67.,   4.,   3.,   3.,   5., 788.,   5.,   3.,
          2.,   4.],
       [  4.,   3.,   3.,  32.,   5.,   5.,   3.,  44.,   4., 446.,  90.,
         44.,  77.]])

In [99]:
fileDataInt = fileData.astype('int32')
fileDataInt

array([[  1,   2,   3,   4,   6,   7,   4,   3,   5,  79,   3,   4,   6],
       [ 43,   4,   6,  67,   4,   3,   3,   5, 788,   5,   3,   2,   4],
       [  4,   3,   3,  32,   5,   5,   3,  44,   4, 446,  90,  44,  77]],
      dtype=int32)

In [100]:
##### Boolean Masking and Advanced Indexing
fileDataInt > 50

array([[False, False, False, False, False, False, False, False, False,
         True, False, False, False],
       [False, False, False,  True, False, False, False, False,  True,
        False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
         True,  True, False,  True]])

In [101]:
fileDataInt[fileDataInt > 50]

array([ 79,  67, 788, 446,  90,  77], dtype=int32)

In [103]:
### You can Index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,7]] # 1,2,7 are index

array([2, 3, 8])

In [108]:
fileDataInt[((fileDataInt > 50) & (fileDataInt < 100))]

array([79, 67, 90, 77], dtype=int32)